/*
 * This source file was generated by the Gradle 'init' task
 */
package com.hrveklesarov;

import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

public class PseudoHardcore extends JavaPlugin {
    @Override
    public void onEnable() {
        Bukkit.getLogger().info("Enabled plugin: " + this.getName());
    }
}
